import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: 1,
    name: "Classic Wayfarer",
    price: 12000.00,
    imageUrl: "https://picsum.photos/id/111/600/600",
    brand: "Ray-Ban",
    category: "Men",
    frameStyle: "Rectangle",
    lensType: "Single Vision",
    faceShape: "Oval",
    style: "Casual",
    description: "Iconic and timeless, the Classic Wayfarer is a staple for any wardrobe. Made with high-quality acetate for durability and comfort.",
    rating: 4.5,
    reviews: 120,
  },
  {
    id: 2,
    name: "Modern Aviator",
    price: 14040.00,
    imageUrl: "https://picsum.photos/id/145/600/600",
    brand: "Oakley",
    category: "Men",
    frameStyle: "Aviator",
    lensType: "Progressive",
    faceShape: "Square",
    style: "Sport",
    description: "A modern take on a classic design. These aviators feature lightweight metal frames and advanced lens technology for superior clarity.",
    rating: 4.8,
    reviews: 95,
  },
  {
    id: 3,
    name: "Hipster Round",
    price: 9600.00,
    imageUrl: "https://picsum.photos/id/164/600/600",
    brand: "Warby Parker",
    category: "Women",
    frameStyle: "Round",
    lensType: "Single Vision",
    faceShape: "Heart",
    style: "Casual",
    description: "Embrace a vintage vibe with these stylish round frames. Perfect for making a statement while ensuring all-day comfort.",
    rating: 4.3,
    reviews: 210,
  },
  {
    id: 4,
    name: "Sleek Cateye",
    price: 16800.00,
    imageUrl: "https://picsum.photos/id/183/600/600",
    brand: "Prada",
    category: "Women",
    frameStyle: "Cat-Eye",
    lensType: "Bifocal",
    faceShape: "Round",
    style: "Luxury",
    description: "Elegant and sophisticated, these cateye glasses add a touch of glamour to any look. Crafted with premium materials for a luxurious feel.",
    rating: 4.9,
    reviews: 78,
  },
  {
    id: 5,
    name: "Urban Explorer",
    price: 12800.00,
    imageUrl: "https://picsum.photos/id/219/600/600",
    brand: "Oakley",
    category: "Men",
    frameStyle: "Rectangle",
    lensType: "Progressive",
    faceShape: "Oval",
    style: "Sport",
    description: "Built for the urban adventurer, these frames are both durable and stylish. They provide a comfortable fit for long days on the go.",
    rating: 4.6,
    reviews: 150,
  },
  {
    id: 6,
    name: "Minimalist Metal",
    price: 10800.00,
    imageUrl: "https://picsum.photos/id/249/600/600",
    brand: "Warby Parker",
    category: "Men",
    frameStyle: "Round",
    lensType: "Single Vision",
    faceShape: "Square",
    style: "Professional",
    description: "Lightweight and minimalist, these metal frames offer a subtle yet sophisticated look. Ideal for those who prefer understated elegance.",
    rating: 4.7,
    reviews: 180,
  },
  {
    id: 7,
    name: "Bold Acetate",
    price: 14400.00,
    imageUrl: "https://picsum.photos/id/257/600/600",
    brand: "Ray-Ban",
    category: "Women",
    frameStyle: "Rectangle",
    lensType: "Bifocal",
    faceShape: "Round",
    style: "Casual",
    description: "Make a bold statement with these thick acetate frames. Designed for those who aren't afraid to stand out from the crowd.",
    rating: 4.4,
    reviews: 132,
  },
  {
    id: 8,
    name: "Vintage Pilot",
    price: 15600.00,
    imageUrl: "https://picsum.photos/id/309/600/600",
    brand: "Prada",
    category: "Women",
    frameStyle: "Aviator",
    lensType: "Progressive",
    faceShape: "Heart",
    style: "Luxury",
    description: "A throwback to classic pilot style, these frames combine vintage aesthetics with modern craftsmanship for a timeless appeal.",
    rating: 4.8,
    reviews: 88,
  },
  {
    id: 9,
    name: "Scholarly Spectacles",
    price: 8800.00,
    imageUrl: "https://picsum.photos/id/312/600/600",
    brand: "Warby Parker",
    category: "Women",
    frameStyle: "Round",
    lensType: "Single Vision",
    faceShape: "Oval",
    style: "Professional",
    description: "Channel your inner intellectual with these scholarly round glasses. A perfect blend of classic style and modern comfort.",
    rating: 4.2,
    reviews: 250,
  },
  {
    id: 10,
    name: "Executive Frame",
    price: 20000.00,
    imageUrl: "https://picsum.photos/id/338/600/600",
    brand: "Prada",
    category: "Men",
    frameStyle: "Rectangle",
    lensType: "Bifocal",
    faceShape: "Square",
    style: "Professional",
    description: "Command the boardroom with these powerful and professional executive frames. Sleek design meets high-performance materials.",
    rating: 4.9,
    reviews: 65,
  },
  {
    id: 11,
    name: "Retro Glam Cateye",
    price: 14800.00,
    imageUrl: "https://picsum.photos/id/342/600/600",
    brand: "Ray-Ban",
    category: "Women",
    frameStyle: "Cat-Eye",
    lensType: "Single Vision",
    faceShape: "Heart",
    style: "Luxury",
    description: "A touch of retro glamour. These cateye frames are perfect for adding a playful yet chic element to your style.",
    rating: 4.7,
    reviews: 92,
  },
  {
    id: 12,
    name: "Sport Performance",
    price: 17600.00,
    imageUrl: "https://picsum.photos/id/355/600/600",
    brand: "Oakley",
    category: "Men",
    frameStyle: "Sport",
    lensType: "Progressive",
    faceShape: "Round",
    style: "Sport",
    description: "Engineered for athletes, these sport performance glasses offer unparalleled durability, comfort, and optical clarity.",
    rating: 4.9,
    reviews: 110,
  },
  {
    id: 13,
    name: "Acuvue Oasys",
    price: 2500.00,
    imageUrl: "https://picsum.photos/id/365/600/600",
    brand: "Acuvue",
    category: "Lenses",
    frameStyle: "Rimless",
    lensType: "Daily",
    faceShape: "Oval",
    style: "Casual",
    description: "Daily disposable contact lenses for ultimate comfort and convenience.",
    rating: 4.9,
    reviews: 500,
  },
  {
    id: 14,
    name: "Biofinity Monthly",
    price: 4500.00,
    imageUrl: "https://picsum.photos/id/366/600/600",
    brand: "CooperVision",
    category: "Lenses",
    frameStyle: "Rimless",
    lensType: "Monthly",
    faceShape: "Round",
    style: "Professional",
    description: "Monthly disposable contact lenses that provide long-lasting comfort.",
    rating: 4.8,
    reviews: 450,
  },
  {
    id: 15,
    name: "Dailies Total1",
    price: 3500.00,
    imageUrl: "https://picsum.photos/id/367/600/600",
    brand: "Alcon",
    category: "Lenses",
    frameStyle: "Rimless",
    lensType: "Daily",
    faceShape: "Square",
    style: "Casual",
    description: "Water gradient technology for exceptional comfort.",
    rating: 4.9,
    reviews: 600,
  },
  {
    id: 16,
    name: "Air Optix",
    price: 4000.00,
    imageUrl: "https://picsum.photos/id/368/600/600",
    brand: "Alcon",
    category: "Lenses",
    frameStyle: "Rimless",
    lensType: "Monthly",
    faceShape: "Heart",
    style: "Professional",
    description: "Breathable contact lenses for healthy eyes.",
    rating: 4.7,
    reviews: 400,
  },
  {
    id: 17,
    name: "Polarized Aviators",
    price: 18000.00,
    imageUrl: "https://picsum.photos/id/145/600/600",
    brand: "Ray-Ban",
    category: "Sunglasses",
    frameStyle: "Aviator",
    lensType: "Single Vision",
    faceShape: "Oval",
    style: "Casual",
    description: "Iconic aviator sunglasses with polarized lenses to reduce glare.",
    rating: 4.9,
    reviews: 300,
  },
  {
    id: 18,
    name: "Holbrook Sunglasses",
    price: 16000.00,
    imageUrl: "https://picsum.photos/id/219/600/600",
    brand: "Oakley",
    category: "Sunglasses",
    frameStyle: "Rectangle",
    lensType: "Single Vision",
    faceShape: "Square",
    style: "Sport",
    description: "A timeless, classic design fused with modern Oakley technology.",
    rating: 4.8,
    reviews: 250,
  },
  {
    id: 19,
    name: "Erika Classic",
    price: 13000.00,
    imageUrl: "https://picsum.photos/id/164/600/600",
    brand: "Ray-Ban",
    category: "Sunglasses",
    frameStyle: "Round",
    lensType: "Single Vision",
    faceShape: "Heart",
    style: "Casual",
    description: "Perfect accessory to complete any look. Features both classic and bright fronts.",
    rating: 4.7,
    reviews: 200,
  },
  {
    id: 20,
    name: "Prada Cinéma",
    price: 25000.00,
    imageUrl: "https://picsum.photos/id/183/600/600",
    brand: "Prada",
    category: "Sunglasses",
    frameStyle: "Cat-Eye",
    lensType: "Single Vision",
    faceShape: "Round",
    style: "Luxury",
    description: "An elegant, sophisticated design from Prada's Cinéma collection.",
    rating: 4.9,
    reviews: 150,
  }
];
